import bcrypt from 'bcryptjs'
import {AuditLog,AuthToken,User} from '../models/index.js'
import {accessToken,findToken,issueToken,verifyRefresh} from '../utils/tokens.js'
import {sendEmail} from '../utils/mailer.js'

export async function register(data,req){if(await User.findOne({where:{email:data.email}})){const error=new Error('Cette adresse e-mail est déjà utilisée');error.status=409;throw error}const user=await User.create({nom:data.nom,prenom:data.prenom,email:data.email,password:await bcrypt.hash(data.password,12),telephone:data.telephone,role:'client'});const verification=await issueToken(user,'verify',req);sendEmail({to:user.email,subject:'Vérifiez votre compte Helmi Travel',html:`<p>Bienvenue ${user.prenom}.</p><p>Votre code de vérification est : <strong>${verification}</strong></p>`}).catch(console.error);return {id:user.id,email:user.email,message:'Compte créé. Vérifiez votre adresse e-mail.'}}
export async function login(data,req){const user=await User.findOne({where:{email:data.email}});if(!user||!await bcrypt.compare(data.password,user.password)){const error=new Error('E-mail ou mot de passe incorrect');error.status=401;throw error}if(!user.email_verifie){const error=new Error('Vérifiez votre adresse e-mail avant de vous connecter');error.status=403;error.code='EMAIL_NOT_VERIFIED';throw error}if(['admin','agent'].includes(user.role))await AuditLog.create({userId:user.id,request_id:req.id,action:'AUTH LOGIN',method:'POST',path:'/api/auth/login',status:200,duration_ms:0,ip:String(req.ip||'').slice(0,45),user_agent:String(req.get('user-agent')||'').slice(0,255),metadata:{role:user.role}});return {token:accessToken(user),refreshToken:await issueToken(user,'refresh',req),user:{id:user.id,nom:user.nom,prenom:user.prenom,email:user.email,role:user.role,email_verifie:user.email_verifie}}}
export async function refresh(raw,req){try{const payload=verifyRefresh(raw);if(payload.type!=='refresh')throw new Error()}catch{const error=new Error('Session expirée');error.status=401;throw error}const record=await findToken(raw,'refresh');if(!record||record.expires_at<new Date()){const error=new Error('Session expirée');error.status=401;throw error}const [revoked]=await AuthToken.update({revoked_at:new Date()},{where:{id:record.id,revoked_at:null}});if(revoked!==1){const error=new Error('Session déjà renouvelée');error.status=401;throw error}const user=await User.findByPk(record.userId);if(!user||!user.email_verifie){const error=new Error('Session invalide');error.status=401;throw error}return {token:accessToken(user),refreshToken:await issueToken(user,'refresh',req)}}
export async function logout(raw){if(!raw)return;const record=await findToken(raw,'refresh');if(record)await record.update({revoked_at:new Date()})}
export async function forgotPassword(email,req){const user=await User.findOne({where:{email}});if(user){const raw=await issueToken(user,'reset',req);sendEmail({to:user.email,subject:'Réinitialisation de votre mot de passe',html:`<p>Utilisez ce code valable 24 heures :</p><p><strong>${raw}</strong></p>`}).catch(console.error)}return {message:'Si ce compte existe, un e-mail a été envoyé.'}}
export async function resetPassword(token,password){const record=await findToken(token,'reset');if(!record||record.expires_at<new Date()){const error=new Error('Lien invalide ou expiré');error.status=400;throw error}const user=await User.findByPk(record.userId);if(!user){const error=new Error('Compte introuvable');error.status=404;throw error}await user.update({password:await bcrypt.hash(password,12)});await AuthToken.update({revoked_at:new Date()},{where:{userId:user.id,revoked_at:null}});return {message:'Mot de passe modifié'}}
export async function verifyEmail(token){const record=await findToken(token,'verify');if(!record||record.expires_at<new Date()){const error=new Error('Code invalide ou expiré');error.status=400;throw error}const user=await User.findByPk(record.userId);await user.update({email_verifie:true});await record.update({revoked_at:new Date()});return {message:'Adresse e-mail vérifiée'}}
export async function resendVerification(email,req){const user=await User.findOne({where:{email}});if(user&&!user.email_verifie){const verification=await issueToken(user,'verify',req);sendEmail({to:user.email,subject:'Nouveau code de vérification Helmi Travel',html:`<p>Bonjour ${user.prenom},</p><p>Votre nouveau code valable 24 heures est : <strong>${verification}</strong></p>`}).catch(console.error)}return {message:'Si ce compte doit être vérifié, un e-mail a été envoyé.'}}
export async function changePassword(userId,currentPassword,password){const user=await User.findByPk(userId);if(!await bcrypt.compare(currentPassword,user.password)){const error=new Error('Mot de passe actuel incorrect');error.status=400;throw error}await user.update({password:await bcrypt.hash(password,12)});await AuthToken.update({revoked_at:new Date()},{where:{userId,type:'refresh',revoked_at:null}});return {message:'Mot de passe modifié, reconnectez-vous.'}}
