import {Op} from 'sequelize'
import {Booking,Destination,Hotel,Review,Room} from '../models/index.js'
const array=value=>Array.isArray(value)?value:String(value||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean)
const normalize=data=>({...data,images:array(data.images||data.image),equipements:array(data.equipements),latitude:data.latitude===''?null:data.latitude,longitude:data.longitude===''?null:data.longitude})
async function withAvailability(hotel,query){if(!query.date_arrivee||!query.date_depart)return hotel;const arrival=new Date(query.date_arrivee),departure=new Date(query.date_depart);if(!(arrival<departure)){const error=new Error('La date de départ doit suivre la date d’arrivée');error.status=422;throw error}const requestedRooms=Math.max(1,Number(query.chambres)||1),people=Math.max(1,Number(query.personnes)||1),capacity=Math.ceil(people/requestedRooms),available=[];for(const room of hotel.Rooms.filter(r=>r.disponible&&r.capacite>=capacity)){const reserved=await Booking.sum('nombre_chambres',{where:{roomId:room.id,status:{[Op.ne]:'annulee'},date_arrivee:{[Op.lt]:query.date_depart},date_depart:{[Op.gt]:query.date_arrivee}}})||0;const remaining=room.quantite-reserved;if(remaining>=requestedRooms)available.push({...room.toJSON(),restantes:remaining})}return {...hotel.toJSON(),availableRooms:available}}
export async function list(query={}){const where={disponibilite:true},number=value=>Number.isFinite(Number(value))?Number(value):null;if(query.destination)where[Op.or]=[{'$Destination.nom$':{[Op.like]:`%${query.destination}%`}},{'$Destination.ville$':{[Op.like]:`%${query.destination}%`}},{'$Destination.pays$':{[Op.like]:`%${query.destination}%`}}];const stars=number(query.etoiles);if(stars&&stars>=1&&stars<=5)where.etoiles=stars;const min=number(query.prix_min),max=number(query.prix_max);if(min!==null||max!==null)where.prix_nuit={...(min!==null?{[Op.gte]:Math.max(0,min)}:{}),...(max!==null?{[Op.lte]:Math.max(0,max)}:{})};if(query.equipement)where.equipements={[Op.like]:`%${String(query.equipement).slice(0,100)}%`};const sorts={prix_asc:['prix_nuit','ASC'],prix_desc:['prix_nuit','DESC'],etoiles:['etoiles','DESC'],recent:['createdAt','DESC']},sort=sorts[query.tri]||sorts.recent;const hotels=await Hotel.findAll({where,include:[Destination,Review,Room],order:[sort]});if(!query.date_arrivee||!query.date_depart)return hotels;const result=[];for(const hotel of hotels){const resolved=await withAvailability(hotel,query);if(resolved.availableRooms.length)result.push(resolved)}return result}
export async function get(id,query={}){const hotel=await Hotel.findByPk(id,{include:[Destination,Review,Room]});return hotel?withAvailability(hotel,query):null}
export const create=data=>Hotel.create(normalize(data))
export async function update(id,data){const item=await Hotel.findByPk(id);if(!item)return null;return item.update(normalize(data))}
export async function remove(id){if(await Booking.count({where:{hotelId:id}})){const error=new Error('Cet hôtel possède un historique de réservations');error.status=409;throw error}return Hotel.destroy({where:{id}})}
