import crypto from 'crypto'
import {sequelize} from '../config/database.js'
import {Invoice,Notification,Order,Payment,WebhookEvent} from '../models/index.js'
import {notify} from './notificationService.js'

const frontend=process.env.FRONTEND_URL||'http://localhost:5173'
const fail=(message,status=400)=>Object.assign(new Error(message),{status})
const currency=()=>String(process.env.PAYMENT_CURRENCY||'').toUpperCase()
function converted(tnd){const rate=Number(process.env.PAYMENT_EXCHANGE_RATE);if(!currency()||!Number.isFinite(rate)||rate<=0)throw fail('Devise de paiement non configurée (PAYMENT_CURRENCY et PAYMENT_EXCHANGE_RATE).',503);return Math.round(Number(tnd)*rate*100)/100}
async function jsonFetch(url,options={}){const response=await fetch(url,options);const body=await response.json().catch(()=>({}));if(!response.ok)throw fail(body.error?.message||body.message||`Erreur fournisseur (${response.status})`,502);return body}
export const configured=method=>method==='stripe'?Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_WEBHOOK_SECRET):method==='paypal'?Boolean(process.env.PAYPAL_CLIENT_ID&&process.env.PAYPAL_CLIENT_SECRET&&process.env.PAYPAL_WEBHOOK_ID):true
async function stripeRequest(path,params,key){return jsonFetch(`https://api.stripe.com/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${process.env.STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded',...(key?{'Idempotency-Key':key}:{})},body:new URLSearchParams(params)})}
const paypalBase=()=>process.env.PAYPAL_MODE==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com'
async function paypalToken(){const basic=Buffer.from(`${process.env.PAYPAL_CLIENT_ID}:${process.env.PAYPAL_CLIENT_SECRET}`).toString('base64');return (await jsonFetch(`${paypalBase()}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'})).access_token}
async function paypalRequest(path,{body,key}={}){return jsonFetch(`${paypalBase()}${path}`,{method:'POST',headers:{Authorization:`Bearer ${await paypalToken()}`,'Content-Type':'application/json',...(key?{'PayPal-Request-Id':key}:{})},body:body?JSON.stringify(body):undefined})}

export async function initiate(order,payment){
  if(!configured(payment.method))throw fail(`${payment.method==='stripe'?'Stripe':'PayPal'} n'est pas configuré.`,503)
  const value=converted(order.montant),code=currency()
  if(payment.method==='stripe'){
    const session=await stripeRequest('checkout/sessions',{mode:'payment',success_url:`${frontend}/compte/paiements?payment=success`,cancel_url:`${frontend}/compte/paiements?payment=cancel`,client_reference_id:order.reference,'metadata[order_id]':String(order.id),'metadata[payment_id]':String(payment.id),'line_items[0][quantity]':'1','line_items[0][price_data][currency]':code.toLowerCase(),'line_items[0][price_data][unit_amount]':String(Math.round(value*100)),'line_items[0][price_data][product_data][name]':order.titre},payment.idempotency_key)
    await payment.update({provider_payment_id:session.id,provider_amount:value,provider_currency:code,provider_metadata:{checkout_url:session.url}});return {paymentId:payment.id,method:'stripe',redirectUrl:session.url}
  }
  const providerOrder=await paypalRequest('/v2/checkout/orders',{key:payment.idempotency_key,body:{intent:'CAPTURE',purchase_units:[{reference_id:String(payment.id),custom_id:String(order.id),invoice_id:order.reference,amount:{currency_code:code,value:value.toFixed(2)},description:order.titre}],payment_source:{paypal:{experience_context:{return_url:`${frontend}/compte/paiements?paypal=return`,cancel_url:`${frontend}/compte/paiements?payment=cancel`,user_action:'PAY_NOW'}}}}})
  const redirectUrl=providerOrder.links?.find(x=>x.rel==='payer-action'||x.rel==='approve')?.href;await payment.update({provider_payment_id:providerOrder.id,provider_amount:value,provider_currency:code});return {paymentId:payment.id,method:'paypal',providerOrderId:providerOrder.id,redirectUrl}
}
export async function finalize(payment,captureId){return sequelize.transaction(async transaction=>{const locked=await Payment.findByPk(payment.id,{transaction,lock:transaction.LOCK.UPDATE});if(locked.status==='paye')return locked;const order=await Order.findByPk(locked.orderId,{transaction,lock:transaction.LOCK.UPDATE});if(!order)throw fail('Dossier introuvable',404);await locked.update({status:'paye',date:new Date(),provider_capture_id:captureId||locked.provider_capture_id,failure_reason:null},{transaction});await order.update({statut:'confirmee'},{transaction});await Invoice.findOrCreate({where:{orderId:order.id},defaults:{orderId:order.id,numero:`FAC-${new Date().getFullYear()}-${order.reference}`,montant_ht:order.montant,taxes:0,montant_ttc:order.montant,date_emission:new Date()},transaction});await notify({userId:order.userId,category:'paiements',titre:'Paiement confirmé',message:`Le paiement du dossier ${order.reference} est confirmé. Votre facture est disponible.`,emailSubject:`Paiement confirmé — ${order.reference}`,emailHtml:`<h2>Paiement confirmé</h2><p>Votre dossier <strong>${order.reference}</strong> est confirmé.</p><p>Montant : <strong>${Number(order.montant).toFixed(2)} ${order.devise}</strong></p><p>Votre facture est disponible dans votre espace Client.</p>`,smsMessage:`Helmi Travel: paiement ${order.reference} confirmé. Facture disponible dans votre espace.`,transaction});return locked})}
function assertAmount(payment,amount,code){if(Number(payment.provider_amount)!==Number(amount)||payment.provider_currency!==String(code).toUpperCase())throw fail('Montant ou devise du fournisseur incohérent',409)}
async function beginEvent(provider,eventId,type,payload){try{return await WebhookEvent.create({provider,event_id:eventId,type,payload_hash:crypto.createHash('sha256').update(payload).digest('hex')})}catch(e){if(e.name==='SequelizeUniqueConstraintError')return null;throw e}}
export function verifyStripe(raw,signature){const values={};for(const part of String(signature||'').split(',')){const [k,v]=part.split('=');if(k&&v&&!values[k])values[k]=v}const timestamp=Number(values.t);if(!process.env.STRIPE_WEBHOOK_SECRET||!timestamp||Math.abs(Date.now()/1000-timestamp)>300)throw fail('Signature Stripe invalide ou expirée',400);const expected=crypto.createHmac('sha256',process.env.STRIPE_WEBHOOK_SECRET).update(`${values.t}.${raw}`).digest('hex'),received=values.v1||'';if(expected.length!==received.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(received)))throw fail('Signature Stripe invalide',400)}
export async function stripeWebhook(raw,signature){verifyStripe(raw,signature);const event=JSON.parse(raw),record=await beginEvent('stripe',event.id,event.type,raw);if(!record)return {duplicate:true};try{const object=event.data?.object;if(event.type==='checkout.session.completed'&&object.payment_status==='paid'){const payment=await Payment.findOne({where:{provider_payment_id:object.id}});if(payment){assertAmount(payment,Number(object.amount_total)/100,object.currency);await finalize(payment,object.payment_intent)}}else if(event.type==='checkout.session.async_payment_failed')await Payment.update({failure_reason:'Paiement Stripe refusé'},{where:{provider_payment_id:object.id}});else if(event.type==='charge.refunded'){const payment=await Payment.findOne({where:{provider_capture_id:object.payment_intent}});if(payment)await payment.update({refunded_amount:Number(object.amount_refunded)/100,refund_status:object.refunded?'total':'partiel'})}await record.update({processed_at:new Date()});return {received:true}}catch(e){await record.destroy();throw e}}
export async function verifyPaypal(headers,event){const result=await paypalRequest('/v1/notifications/verify-webhook-signature',{body:{auth_algo:headers['paypal-auth-algo'],cert_url:headers['paypal-cert-url'],transmission_id:headers['paypal-transmission-id'],transmission_sig:headers['paypal-transmission-sig'],transmission_time:headers['paypal-transmission-time'],webhook_id:process.env.PAYPAL_WEBHOOK_ID,webhook_event:event}});if(result.verification_status!=='SUCCESS')throw fail('Signature PayPal invalide',400)}
export async function paypalWebhook(headers,event){await verifyPaypal(headers,event);const raw=JSON.stringify(event),record=await beginEvent('paypal',event.id,event.event_type,raw);if(!record)return {duplicate:true};try{const resource=event.resource||{};if(event.event_type==='PAYMENT.CAPTURE.COMPLETED'){const payment=await Payment.findOne({where:{provider_payment_id:resource.supplementary_data?.related_ids?.order_id}});if(payment){assertAmount(payment,resource.amount?.value,resource.amount?.currency_code);await finalize(payment,resource.id)}}else if(event.event_type==='PAYMENT.CAPTURE.REFUNDED'){const captureId=resource.links?.find(x=>x.rel==='up')?.href?.split('/').pop(),payment=await Payment.findOne({where:{provider_capture_id:captureId}});if(payment){const total=Number(payment.refunded_amount||0)+Number(resource.amount?.value||0);await payment.update({refunded_amount:total,refund_status:total>=Number(payment.provider_amount)?'total':'partiel'})}}await record.update({processed_at:new Date()});return {received:true}}catch(e){await record.destroy();throw e}}
export async function capturePaypal(userId,providerOrderId){const payment=await Payment.findOne({where:{provider_payment_id:providerOrderId},include:{model:Order,where:{userId}}});if(!payment)throw fail('Paiement PayPal introuvable',404);if(payment.status==='paye')return payment;const result=await paypalRequest(`/v2/checkout/orders/${encodeURIComponent(providerOrderId)}/capture`,{key:`capture-${payment.idempotency_key}`}),capture=result.purchase_units?.[0]?.payments?.captures?.[0];if(capture?.status!=='COMPLETED')throw fail('Capture PayPal non terminée',409);assertAmount(payment,capture.amount.value,capture.amount.currency_code);return finalize(payment,capture.id)}
export async function refund(paymentId,amount){const payment=await Payment.findByPk(paymentId,{include:Order});if(!payment||payment.status!=='paye'||!payment.provider_capture_id)throw fail('Paiement remboursable introuvable',409);const remaining=Number(payment.provider_amount)-Number(payment.refunded_amount||0),value=amount==null?remaining:Number(amount);if(value<=0||value>remaining)throw fail('Montant de remboursement invalide',400);let result;if(payment.method==='stripe')result=await stripeRequest('refunds',{payment_intent:payment.provider_capture_id,amount:String(Math.round(value*100))},`refund-${payment.id}-${payment.refunded_amount}-${value}`);else if(payment.method==='paypal')result=await paypalRequest(`/v2/payments/captures/${encodeURIComponent(payment.provider_capture_id)}/refund`,{key:`refund-${payment.id}-${payment.refunded_amount}-${value}`,body:{amount:{value:value.toFixed(2),currency_code:payment.provider_currency}}});else throw fail('Le remboursement en agence doit être traité hors ligne',409);const refunded=Number(payment.refunded_amount||0)+value;await payment.update({refunded_amount:refunded,refund_status:refunded>=Number(payment.provider_amount)?'total':'partiel',provider_metadata:{...(payment.provider_metadata||{}),last_refund_id:result.id}});return payment}
