import {Op,fn,col,where as sqlWhere} from 'sequelize'
import {Booking,Destination,Review,Trip} from '../models/index.js'
const array=value=>Array.isArray(value)?value:String(value||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean)
function program(value){if(Array.isArray(value))return value;try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed}catch{}return String(value||'').split('\n').filter(Boolean).map((line,index)=>{const parts=line.replace(/^Jour\s*\d+\s*[:—-]?\s*/i,'').split('|');return {jour:index+1,titre:parts[0]?.trim(),description:parts.slice(1).join('|').trim()}})}
const normalize=data=>({...data,galerie:array(data.galerie),repas_inclus:array(data.repas_inclus),programme:program(data.programme)})
export const list=(query={})=>{const filters={statut:'publie'},and=[],number=value=>Number.isFinite(Number(value))?Number(value):null;if(query.destination)filters[Op.or]=[{'$Destination.nom$':{[Op.like]:`%${query.destination}%`}},{'$Destination.ville$':{[Op.like]:`%${query.destination}%`}},{'$Destination.pays$':{[Op.like]:`%${query.destination}%`}}];const min=number(query.prix_min),max=number(query.prix_max);if(min!==null||max!==null)filters.prix={...(min!==null?{[Op.gte]:Math.max(0,min)}:{}),...(max!==null?{[Op.lte]:Math.max(0,max)}:{})};const from=query.date_depart||query.date_depart_min,to=query.date_depart_max;if(from||to)filters.date_depart={...(from?{[Op.gte]:from}:{}),...(to?{[Op.lte]:to}:{})};if(query.date_retour_max)filters.date_retour={[Op.lte]:query.date_retour_max};const people=number(query.personnes);if(people&&people>0)filters.places={[Op.gte]:people};if(query.type_voyage)filters.type_voyage={[Op.like]:`%${String(query.type_voyage).slice(0,100)}%`};if(query.transport)filters.transport={[Op.like]:`%${String(query.transport).slice(0,100)}%`};const duration=fn('DATEDIFF',col('date_retour'),col('date_depart')),durationMin=number(query.duree_min),durationMax=number(query.duree_max);if(durationMin!==null)and.push(sqlWhere(duration,{[Op.gte]:Math.max(0,durationMin-1)}));if(durationMax!==null)and.push(sqlWhere(duration,{[Op.lte]:Math.max(0,durationMax-1)}));if(and.length)filters[Op.and]=and;const sorts={prix_asc:['prix','ASC'],prix_desc:['prix','DESC'],date:['date_depart','ASC'],duree:['date_retour','ASC']},sort=sorts[query.tri]||sorts.date;return Trip.findAll({where:filters,include:[Destination,Review],order:[sort]})}
export const get=id=>Trip.findByPk(id,{include:{all:true}})
export const create=data=>Trip.create(normalize(data))
export async function update(id,data){const item=await Trip.findByPk(id);if(!item)return null;return item.update(normalize(data))}
export async function remove(id){if(await Booking.count({where:{tripId:id}})){const error=new Error('Ce voyage possède un historique de réservations');error.status=409;throw error}return Trip.destroy({where:{id}})}
