import {User,Hotel,Trip,Booking,Payment,Notification,Invoice} from '../models/index.js'
import {paymentEmail} from '../utils/mailer.js'
import {invoicePdf} from '../utils/pdf.js'

export async function createPayment(req,res,next){try{if(!['stripe','paypal','agence'].includes(req.body.method))return res.status(400).json({message:'Méthode de paiement invalide'});const booking=await Booking.findByPk(req.body.booking_id);if(!booking||booking.userId!==req.user.id)return res.sendStatus(403);if(['annulee','terminee'].includes(booking.status))return res.status(409).json({message:'Cette réservation ne peut plus être payée'});if(await Payment.findOne({where:{bookingId:booking.id}}))return res.status(409).json({message:'Un paiement existe déjà pour cette réservation'});const payment=await Payment.create({bookingId:booking.id,method:req.body.method,amount:booking.prix_total,status:'en_attente',date:new Date()});await Notification.create({userId:req.user.id,titre:'Paiement initié',message:`Votre paiement de ${Number(booking.prix_total).toFixed(2)} DT est en cours de validation.`,type:'paiement'});res.status(201).json(payment)}catch(e){next(e)}}
export async function myPayments(req,res,next){try{res.json(await Payment.findAll({include:{model:Booking,where:{userId:req.user.id},include:[Hotel,Trip,Invoice]},order:[['createdAt','DESC']]}))}catch(e){next(e)}}
export async function adminPayments(req,res,next){try{res.json(await Payment.findAll({include:{model:Booking,include:[{model:User,attributes:['id','nom','prenom','email']},Hotel,Trip]},order:[['createdAt','DESC']]}))}catch(e){next(e)}}
export async function updatePaymentStatus(req,res,next){try{if(!['en_attente','paye','annule'].includes(req.body.status))return res.status(400).json({message:'Statut invalide'});const item=await Payment.findByPk(req.params.id);if(!item)return res.sendStatus(404);await item.update({status:req.body.status,date:new Date()});const booking=await Booking.findByPk(item.bookingId,{include:[User]});if(req.body.status==='paye'){await booking.update({status:'confirmee'});await Invoice.findOrCreate({where:{bookingId:booking.id},defaults:{numero:`FAC-${new Date().getFullYear()}-${String(booking.id).padStart(5,'0')}`,montant_ht:booking.prix_total,taxes:0,montant_ttc:booking.prix_total,date_emission:new Date()}})}await Notification.create({userId:booking.userId,titre:`Paiement ${req.body.status}`,message:`Le paiement de ${Number(item.amount).toFixed(2)} DT pour la réservation HT-${String(booking.id).padStart(5,'0')} est ${req.body.status}.`,type:'paiement'});paymentEmail(booking.User,booking,req.body.status).catch(console.error);res.json(item)}catch(e){next(e)}}
export async function invoiceDocument(req,res,next){try{const invoice=await Invoice.findByPk(req.params.id,{include:{model:Booking,include:[User,Hotel,Trip,Payment]}});if(!invoice)return res.sendStatus(404);if(invoice.Booking.userId!==req.user.id&&!['admin','agent'].includes(req.user.role))return res.sendStatus(403);await invoicePdf(res,invoice)}catch(e){next(e)}}
