import {body,validationResult} from 'express-validator'
import xss from 'xss'

export const validate=(req,res,next)=>{const errors=validationResult(req);if(!errors.isEmpty())return res.status(422).json({message:'Données invalides',errors:errors.array().map(({path,msg})=>({field:path,message:msg}))});next()}
export const registerRules=[body('nom').trim().isLength({min:2,max:80}),body('prenom').trim().isLength({min:2,max:80}),body('email').trim().isEmail().normalizeEmail(),body('password').isLength({min:8,max:128}).matches(/[A-Za-z]/).matches(/[0-9]/),validate]
export const loginRules=[body('email').trim().isEmail().normalizeEmail(),body('password').isString().notEmpty(),validate]
export const emailRule=[body('email').trim().isEmail().normalizeEmail(),validate]
export const passwordRules=[body('password').isLength({min:8,max:128}).matches(/[A-Za-z]/).matches(/[0-9]/),validate]
export const tokenRules=[body('token').isString().isLength({min:32,max:4096}),validate]
export const refreshRules=[body('refreshToken').isString().isLength({min:32,max:4096}),validate]
export const changePasswordRules=[body('currentPassword').isString().isLength({min:1,max:128}),body('password').isLength({min:8,max:128}).matches(/[A-Za-z]/).matches(/[0-9]/),validate]
export function sanitize(req,res,next){const clean=value=>{if(typeof value==='string')return xss(value.trim());if(Array.isArray(value))return value.map(clean);if(value&&typeof value==='object')for(const key of Object.keys(value)){if(key.includes('$')||key.includes('.'))delete value[key];else value[key]=clean(value[key])}return value};req.body=clean(req.body||{});req.query=clean(req.query||{});next()}
export function validatePayload(req,res,next){if(!['POST','PUT','PATCH'].includes(req.method))return next();const errors=[];const walk=(value,path='',depth=0)=>{if(depth>5){errors.push(`${path}: structure trop profonde`);return}if(typeof value==='string'&&value.length>10000)errors.push(`${path}: texte trop long`);if(Array.isArray(value)){if(value.length>100)errors.push(`${path}: trop d’éléments`);value.forEach((v,i)=>walk(v,`${path}[${i}]`,depth+1))}else if(value&&typeof value==='object')Object.entries(value).forEach(([k,v])=>walk(v,path?`${path}.${k}`:k,depth+1))};walk(req.body);for(const key of ['id','userId','hotelId','tripId','destinationId','booking_id','nombre_personnes','nuits','places','capacite'])if(req.body[key]!==undefined&&(!Number.isFinite(Number(req.body[key]))||Number(req.body[key])<0))errors.push(`${key}: nombre invalide`);for(const key of ['prix','prix_nuit','amount','valeur'])if(req.body[key]!==undefined&&Number(req.body[key])<0)errors.push(`${key}: valeur négative interdite`);if(req.body.rating!==undefined&&(!Number.isInteger(Number(req.body.rating))||Number(req.body.rating)<1||Number(req.body.rating)>5))errors.push('rating: note entre 1 et 5 requise');if(errors.length)return res.status(422).json({message:'Données invalides',errors:errors.map(message=>({message}))});next()}
