import PDFDocument from 'pdfkit'
import {Setting} from '../models/index.js'
const navy='#071b33',gold='#d8ad5f',ink='#152238',muted='#6d7887',cream='#f7f4ee'
const money=(value,currency='TND')=>`${Number(value||0).toFixed(2)} ${currency}`
const date=value=>value?new Date(value).toLocaleDateString('fr-FR'):'—'
const ref=id=>`HT-${String(id).padStart(5,'0')}`
const status=value=>String(value||'—').replaceAll('_',' ').replace(/^./,x=>x.toUpperCase())
async function agency(){const rows=await Setting.findAll(),values=Object.fromEntries(rows.map(x=>[x.cle,x.valeur]));return {name:values.agence_nom||'Helmi Travel',address:values.agence_adresse||'12 Avenue Habib Bourguiba, Tunis',phone:values.agence_telephone||'+216 71 000 700',email:values.agence_email||'contact@helmitravel.tn',taxId:values.matricule_fiscal||'Matricule fiscal à compléter',website:values.agence_site||'www.helmitravel.tn'}}
function create(res,filename,title,info){const doc=new PDFDocument({size:'A4',margin:45,bufferPages:true,info:{Title:title,Author:info.name,Creator:'Helmi Travel'}});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${filename}"`);res.setHeader('Cache-Control','private, no-store');doc.pipe(res);pageHeader(doc,title,info);return doc}
function pageHeader(doc,title,info){doc.rect(0,0,612,108).fill(navy);doc.fillColor(gold).font('Helvetica-Bold').fontSize(24).text(info.name.toUpperCase(),45,30);doc.fillColor('#fff').font('Helvetica').fontSize(10).text(title,45,68);doc.fillColor('#dce4ed').fontSize(8).text(`${info.email}  •  ${info.phone}`,360,38,{width:205,align:'right'});doc.fillColor(ink);doc.y=130}
function pageFooter(doc,info){const range=doc.bufferedPageRange();for(let i=range.start;i<range.start+range.count;i++){doc.switchToPage(i);doc.moveTo(45,790).lineTo(550,790).strokeColor('#dedede').stroke();doc.fillColor(muted).font('Helvetica').fontSize(8).text(`${info.name} • ${info.address} • ${info.taxId}`,45,800,{width:430});doc.text(`Page ${i+1}/${range.count}`,475,800,{width:75,align:'right'})}}
function finish(doc,info){pageFooter(doc,info);doc.end()}
function title(doc,text,subtitle){doc.fillColor(navy).font('Helvetica-Bold').fontSize(20).text(text);if(subtitle)doc.fillColor(muted).font('Helvetica').fontSize(9).text(subtitle);doc.moveDown(1.2)}
function section(doc,text){if(doc.y>700){doc.addPage();pageHeader(doc,'DOCUMENT HELMI TRAVEL',doc._agency)}doc.fillColor(gold).font('Helvetica-Bold').fontSize(10).text(text.toUpperCase());doc.moveTo(45,doc.y+4).lineTo(550,doc.y+4).strokeColor('#ead8b8').stroke();doc.moveDown(1)}
function row(doc,label,value){doc.fillColor(muted).font('Helvetica').fontSize(9).text(label,45,doc.y,{width:150,continued:true});doc.fillColor(ink).font('Helvetica-Bold').text(String(value??'—'),195,doc.y,{width:350});doc.moveDown(.45)}
function totalBox(doc,label,value){doc.moveDown();const y=doc.y;doc.rect(45,y,505,64).fill(cream);doc.fillColor(navy).font('Helvetica-Bold').fontSize(13).text(label,65,y+20);doc.fontSize(21).text(value,335,y+15,{width:190,align:'right'});doc.y=y+82}

export async function confirmationPdf(res,booking){const info=await agency(),doc=create(res,`confirmation-${ref(booking.id)}.pdf`,'CONFIRMATION DE RÉSERVATION',info);doc._agency=info;title(doc,`Réservation ${ref(booking.id)}`,`Document généré le ${date(new Date())}`);section(doc,'Client');row(doc,'Nom',`${booking.User.prenom} ${booking.User.nom}`);row(doc,'E-mail',booking.User.email);row(doc,'Téléphone',booking.User.telephone||'—');section(doc,'Prestation');row(doc,'Offre',booking.Hotel?.nom||booking.Trip?.titre||'Offre Helmi Travel');row(doc,'Date de réservation',date(booking.date));row(doc,'Voyageurs',booking.nombre_personnes);if(booking.date_arrivee)row(doc,'Séjour',`${date(booking.date_arrivee)} au ${date(booking.date_depart)}`);row(doc,'Statut',status(booking.status));totalBox(doc,'Montant total',money(booking.prix_total));doc.fillColor(muted).font('Helvetica').fontSize(9).text('Cette confirmation atteste l’enregistrement de la demande. La prestation devient définitive selon son statut et les conditions de paiement.',45,doc.y,{width:505,align:'justify'});finish(doc,info)}

export async function invoicePdf(res,invoice){const booking=invoice.Booking,info=await agency(),doc=create(res,`facture-${invoice.numero}.pdf`,'FACTURE',info);doc._agency=info;title(doc,invoice.numero,`Émise le ${date(invoice.date_emission)}`);section(doc,'Émetteur et client');row(doc,'Émetteur',`${info.name} — ${info.taxId}`);row(doc,'Facturé à',`${booking.User.prenom} ${booking.User.nom}`);row(doc,'E-mail',booking.User.email);section(doc,'Détail');row(doc,'Référence',ref(booking.id));row(doc,'Prestation',booking.Hotel?.nom||booking.Trip?.titre||'Réservation Helmi Travel');row(doc,'Montant HT',money(invoice.montant_ht));row(doc,'Taxes',money(invoice.taxes));totalBox(doc,'TOTAL TTC',money(invoice.montant_ttc));row(doc,'Paiement',booking.Payment?`${booking.Payment.method.toUpperCase()} — ${status(booking.Payment.status)}`:'—');doc.fillColor(muted).font('Helvetica').fontSize(8).text('Facture électronique générée par Helmi Travel. Conservez ce document comme justificatif.',45,doc.y,{width:505});finish(doc,info)}

export async function tripProgramPdf(res,trip){const info=await agency(),doc=create(res,`programme-voyage-${trip.id}.pdf`,'PROGRAMME DE VOYAGE',info);doc._agency=info;title(doc,trip.titre,`${date(trip.date_depart)} — ${date(trip.date_retour)}`);section(doc,'Informations pratiques');row(doc,'Destination',trip.Destination?`${trip.Destination.nom}, ${trip.Destination.pays}`:'—');row(doc,'Transport',trip.transport||'Selon programme');row(doc,'Hôtel inclus',trip.hotel_inclus||'Selon programme');row(doc,'Repas',(trip.repas_inclus||[]).join(', ')||'Selon programme');row(doc,'Prix indicatif',money(trip.prix));doc.moveDown();section(doc,'Programme jour par jour');for(const day of trip.programme||[]){if(doc.y>715){doc.addPage();pageHeader(doc,'PROGRAMME DE VOYAGE',info)}doc.fillColor(navy).font('Helvetica-Bold').fontSize(12).text(`Jour ${day.jour} — ${day.titre||'Programme'}`);if(day.description)doc.fillColor(ink).font('Helvetica').fontSize(9.5).text(day.description,{lineGap:3,align:'justify'});doc.moveDown(.9)}doc.fillColor(muted).font('Helvetica-Oblique').fontSize(8).text('Le programme peut être adapté selon les conditions locales, impératifs opérationnels ou événements indépendants de la volonté de l’agence.',45,doc.y,{width:505});finish(doc,info)}

export async function carContractPdf(res,booking){const car=booking.Car,days=Math.ceil((new Date(booking.date_fin)-new Date(booking.date_debut))/86400000),info=await agency(),doc=create(res,`contrat-location-${booking.id}.pdf`,'CONTRAT DE LOCATION DE VÉHICULE',info);doc._agency=info;title(doc,`Contrat LOC-${String(booking.id).padStart(5,'0')}`,`Établi le ${date(new Date())}`);section(doc,'Locataire');row(doc,'Client',`${booking.User.prenom} ${booking.User.nom}`);row(doc,'Conducteur',booking.conducteur_nom);row(doc,'Document',booking.conducteur_document);row(doc,'Téléphone',booking.telephone);section(doc,'Véhicule et période');row(doc,'Véhicule',`${car.marque} ${car.modele}`);row(doc,'Catégorie',car.CarCategory?.nom||'—');row(doc,'Transmission / carburant',`${car.transmission||'—'} / ${car.carburant||'—'}`);row(doc,'Prise en charge',car.lieu||info.address);row(doc,'Période',`${date(booking.date_debut)} au ${date(booking.date_fin)} — ${days} jour(s)`);row(doc,'Statut',status(booking.statut));totalBox(doc,'Montant contractuel',money(booking.prix_total));section(doc,'Conditions principales');doc.fillColor(ink).font('Helvetica').fontSize(8.5).list(['Le conducteur doit présenter un permis valide et le document déclaré au contrat.','Le véhicule doit être restitué à la date, au lieu et dans l’état convenus.','Les dommages, infractions, frais de carburant et retards peuvent être facturés au locataire.','Le contrat reste soumis aux conditions générales remises par l’agence.'],{bulletRadius:2,textIndent:12,lineGap:4});doc.moveDown(1.5);doc.font('Helvetica-Bold').text('Signature du locataire',60,700).text('Signature de l’agence',365,700);doc.moveTo(45,755).lineTo(240,755).strokeColor('#999').stroke();doc.moveTo(350,755).lineTo(545,755).stroke();finish(doc,info)}

export async function orderConfirmationPdf(res,order){const info=await agency(),doc=create(res,`confirmation-${order.reference}.pdf`,'CONFIRMATION DE DOSSIER',info);doc._agency=info;title(doc,order.reference,`Créé le ${date(order.createdAt)}`);section(doc,'Client');row(doc,'Nom',`${order.User.prenom} ${order.User.nom}`);row(doc,'E-mail',order.User.email);section(doc,'Dossier');row(doc,'Service',status(order.type));row(doc,'Prestation',order.titre);row(doc,'Voyageurs',typeof order.voyageurs==='object'?JSON.stringify(order.voyageurs):order.voyageurs||'—');row(doc,'Statut',status(order.statut));if(order.Payment)row(doc,'Paiement',`${order.Payment.method.toUpperCase()} — ${status(order.Payment.status)}`);totalBox(doc,'Montant total',money(order.montant,order.devise));doc.fillColor(muted).font('Helvetica').fontSize(9).text('Document électronique de confirmation. Consultez votre espace Client pour le statut actualisé et la facture.',45,doc.y,{width:505});finish(doc,info)}

export async function orderInvoicePdf(res,invoice){const order=invoice.Order,info=await agency(),doc=create(res,`facture-${invoice.numero}.pdf`,'FACTURE',info);doc._agency=info;title(doc,invoice.numero,`Émise le ${date(invoice.date_emission)}`);section(doc,'Facturation');row(doc,'Émetteur',`${info.name} — ${info.taxId}`);row(doc,'Client',`${order.User.prenom} ${order.User.nom}`);row(doc,'E-mail',order.User.email);row(doc,'Dossier',order.reference);section(doc,'Prestation');row(doc,'Description',order.titre);row(doc,'Type',status(order.type));row(doc,'Montant HT',money(invoice.montant_ht,order.devise));row(doc,'Taxes',money(invoice.taxes,order.devise));totalBox(doc,'TOTAL TTC',money(invoice.montant_ttc,order.devise));if(order.Payment){row(doc,'Méthode',order.Payment.method.toUpperCase());row(doc,'Statut du paiement',status(order.Payment.status));row(doc,'Date du paiement',date(order.Payment.date));if(Number(order.Payment.refunded_amount)>0)row(doc,'Remboursé',money(order.Payment.refunded_amount,order.Payment.provider_currency))}doc.fillColor(muted).font('Helvetica').fontSize(8).text('Facture électronique générée par Helmi Travel.',45,doc.y,{width:505});finish(doc,info)}
